In [1]:
pip install numpy

In [19]:
import numpy as np

In [2]:
np.array([2,13,4,2,4,1])

array([ 2, 13,  4,  2,  4,  1])

In [3]:
type(np.array([2,13,4,2,4,1]))

numpy.ndarray

In [4]:
np.array([[13213,1242141,24214],[21421,14,123]])

array([[  13213, 1242141,   24214],
       [  21421,      14,     123]])

In [5]:
type(np.array([[132,1242,2],[21,1,12]]))

numpy.ndarray

In [6]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [7]:

arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
#to find dim of array
arr.ndim

2

In [9]:
# extracting data out of array
arr[1][1]

6

In [10]:
arr[1][3]

8

In [11]:
arr[0]

array([1, 2, 3, 4])

In [12]:
#setting dimension of an array
# dont use ndim or dim it is dmin
arr = np.array([1,2,3] , ndmin =3)

In [13]:
arr

array([[[1, 2, 3]]])

In [14]:
arr = np.array([[1,2,4],[4,5,6],[7,8,9]])

In [15]:
arr.ndim

2

In [16]:
# how to represent  3d array
#to generate random data set 

In [17]:
np.random.randint(1,15,(3,2)) # gives 3X2 array with values ranging from 1 to 15

array([[13, 14],
       [ 6,  2],
       [12, 12]])

In [18]:
np.random.randint(21,45,(3,6,4))

array([[[32, 36, 30, 41],
        [22, 26, 21, 44],
        [24, 42, 31, 38],
        [25, 22, 30, 24],
        [31, 33, 41, 28],
        [42, 35, 41, 23]],

       [[22, 41, 37, 43],
        [37, 35, 28, 35],
        [25, 22, 44, 24],
        [21, 32, 31, 34],
        [41, 29, 33, 44],
        [28, 38, 37, 22]],

       [[26, 31, 29, 29],
        [21, 33, 33, 44],
        [23, 31, 25, 31],
        [41, 24, 21, 39],
        [21, 27, 33, 35],
        [44, 31, 40, 22]]])

In [20]:
# When element is string
l=[1,2,3,4]
k=[1,2,'andy',4]

In [21]:
np.array(l)

array([1, 2, 3, 4])

In [23]:
np.array(k)
# It is actually converting everything into string automatically so that each is converted into one data type of higher order

array(['1', '2', 'andy', '4'], dtype='<U11')

In [29]:
 arr = np.array([[[[1,2,3],[4,5,6]]]])

In [30]:
arr.ndim

4

In [32]:
l1 = [4,5,6,7,"sudh" , 34.565, True]
a1 = np.array(l1)
a2 = np.array([[1,2,3] , [4,5,6]])
a3 = np.array([[[1,2,3] , [4,5,6] , [7,8,9]]])

In [33]:
a1.size

7

In [34]:
a2.size

6

In [35]:
a3.size

9

In [36]:
a1.shape   #(x)

(7,)

In [43]:
a2.shape  #(y,x) 
# 2 row 3 column  or 2X3 mat

(2, 3)

In [44]:
a3.shape  #(z,y,x) 
# in 1 sheet 3 row 3 column so 1 3X3 Matrix

(1, 3, 3)

In [55]:
# To generate random data from integer, bool , z scores etc.
np.random.randint(2,20) 
#between 2 and 20

8

In [56]:
# to generate data with a specific dimn
#say we want 3 rows and 4 columns
np.random.randint(2,10,(3,4))

array([[5, 9, 8, 6],
       [8, 7, 7, 8],
       [7, 3, 7, 5]])

In [59]:
# to generate 3 d data
np.random.randint(2,10,(2,3,4))

array([[[2, 3, 6, 3],
        [2, 5, 2, 4],
        [8, 8, 4, 7]],

       [[4, 9, 3, 6],
        [7, 2, 9, 5],
        [7, 4, 8, 8]]])

In [62]:
# random data with any dtype
np.random.rand(2,3)
#rand func is for matrix 

array([[0.16506027, 0.75410222, 0.50949012],
       [0.50306272, 0.43725527, 0.62205546]])

In [65]:
# randn function
np.random.randn(3,3)

array([[-0.54238264, -0.64642095, -0.29991664],
       [ 0.8813225 ,  1.3092885 ,  1.42315423],
       [ 0.39067628, -2.24585045,  0.4529715 ]])

In [66]:
'''
randn for normal data
randint for integers
'''

'\nrandn for normal data\nrandint for integers\n'

In [72]:
# to change shape or reshape of matrix
a4 = np.random.randn(3,4)
#12 elements

In [73]:
a4

array([[ 0.14159267, -0.06844689, -0.15180971, -0.19786757],
       [-0.5664329 ,  1.11268247, -0.14272796,  0.54933092],
       [-0.72465269,  0.20164872, -0.00459727,  1.17518854]])

In [74]:
a4.reshape(6,2)
# it will not work as in total it will be able to accomodate 12 data elements whereas originally we had 9 elements so we need to choose such that we have 9 elements in reshaped dataset

array([[ 0.14159267, -0.06844689],
       [-0.15180971, -0.19786757],
       [-0.5664329 ,  1.11268247],
       [-0.14272796,  0.54933092],
       [-0.72465269,  0.20164872],
       [-0.00459727,  1.17518854]])

In [75]:
a4.reshape(2,-1)
# here it is expecting 6 at place of -1 so it automatically detect a possible no so that all 12 elts rrepresented

array([[ 0.14159267, -0.06844689, -0.15180971, -0.19786757, -0.5664329 ,
         1.11268247],
       [-0.14272796,  0.54933092, -0.72465269,  0.20164872, -0.00459727,
         1.17518854]])

In [77]:
# say we want reshape in 3d then:
a4.reshape(3,2,2)

array([[[ 0.14159267, -0.06844689],
        [-0.15180971, -0.19786757]],

       [[-0.5664329 ,  1.11268247],
        [-0.14272796,  0.54933092]],

       [[-0.72465269,  0.20164872],
        [-0.00459727,  1.17518854]]])

In [78]:
a1

array(['4', '5', '6', '7', 'sudh', '34.565', 'True'], dtype='<U32')

In [80]:
a1[4] = 'andy'

In [81]:
a1

array(['4', '5', '6', '7', 'andy', '34.565', 'True'], dtype='<U32')

In [82]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [114]:
# for filtering 3d
a3[:,:,1:]

array([[[2, 3],
        [5, 6],
        [8, 9]]])

In [110]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [107]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [108]:
a2[[0,1] , 1:]

array([[2, 3],
       [5, 6]])

In [115]:
a5 = np.random.randint(2,90 , (6,5))

In [116]:
a5

array([[60, 50, 59, 22, 89],
       [62,  2, 26, 49, 71],
       [21, 62, 16, 40,  9],
       [81, 45, 32, 38, 67],
       [80, 38, 86,  9, 72],
       [73, 87,  3, 55, 37]])

In [117]:
# to filter all values  > 40 in a5
a5[a5>40]

array([60, 50, 59, 89, 62, 49, 71, 62, 81, 45, 67, 80, 86, 72, 73, 87, 55])

In [118]:
# cahnge value
a5[0,1] = 200

In [119]:
a5

array([[ 60, 200,  59,  22,  89],
       [ 62,   2,  26,  49,  71],
       [ 21,  62,  16,  40,   9],
       [ 81,  45,  32,  38,  67],
       [ 80,  38,  86,   9,  72],
       [ 73,  87,   3,  55,  37]])

In [138]:
a6 = np.random.randint(0,3,(3,3))

In [139]:
a7 = np.random.randint(0,3,(3,3))

In [140]:
a6

array([[2, 1, 1],
       [0, 0, 0],
       [0, 0, 2]])

In [141]:
a7

array([[0, 0, 2],
       [1, 2, 1],
       [0, 2, 1]])

In [143]:
a6*a7
# THIS IS ELEMENT MULTIPLICATION

array([[0, 0, 2],
       [0, 0, 0],
       [0, 0, 2]])

In [144]:
a8 = np.random.randint(0,3,(3,4))

In [145]:
a8

array([[0, 0, 2, 2],
       [0, 0, 1, 1],
       [0, 2, 1, 0]])

In [146]:
a6*a8
# could not multiply if column of 1st not equal to row of second

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [148]:
a6@a7
#MATRIX MULTIPLICATION

array([[1, 4, 6],
       [0, 0, 0],
       [0, 4, 2]])

In [149]:
a6@a8

array([[0, 2, 6, 5],
       [0, 0, 0, 0],
       [0, 4, 2, 0]])

In [152]:
# also we can use for dot product
np.dot(a6,a8)

array([[0, 2, 6, 5],
       [0, 0, 0, 0],
       [0, 4, 2, 0]])

In [153]:
#also
np.matmul(a6,a8)

array([[0, 2, 6, 5],
       [0, 0, 0, 0],
       [0, 4, 2, 0]])

In [155]:
# for Element wise
np.multiply(a6,a7)

array([[0, 0, 2],
       [0, 0, 0],
       [0, 0, 2]])

In [156]:
a6+100

array([[102, 101, 101],
       [100, 100, 100],
       [100, 100, 102]])

In [157]:
a6*2

array([[4, 2, 2],
       [0, 0, 0],
       [0, 0, 4]])

In [158]:
a6-a7

array([[ 2,  1, -1],
       [-1, -2, -1],
       [ 0, -2,  1]])

In [159]:
a6+a7

array([[2, 1, 3],
       [1, 2, 1],
       [0, 2, 3]])

In [160]:
a6/0

C:\Users\HP\AppData\Local\Temp\ipykernel_9360\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\HP\AppData\Local\Temp\ipykernel_9360\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, inf, inf],
       [nan, nan, nan],
       [nan, nan, inf]])

In [162]:
a6**3

array([[8, 1, 1],
       [0, 0, 0],
       [0, 0, 8]], dtype=int32)

In [167]:
# zeros and ones function
a8 = np.zeros((3,4))

In [168]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [169]:
a9 = np.ones((3,3))

In [170]:
a9

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [171]:
a9+10

array([[11., 11., 11.],
       [11., 11., 11.],
       [11., 11., 11.]])

In [173]:
a9 + np.array([1,2,3])
# same elements sholud be there 

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [183]:
# column wise broadcasting operations
a10 = np.array([[1,2,3]])
# Shold be 2 dim to rotate

In [184]:
a10

array([[1, 2, 3]])

In [185]:
# first rotate it TRANSPOSE
a10.T

array([[1],
       [2],
       [3]])

In [186]:
a9 + a10.T

array([[2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [187]:
a5

array([[ 60, 200,  59,  22,  89],
       [ 62,   2,  26,  49,  71],
       [ 21,  62,  16,  40,   9],
       [ 81,  45,  32,  38,  67],
       [ 80,  38,  86,   9,  72],
       [ 73,  87,   3,  55,  37]])

In [188]:
# for square root of each element
np.sqrt(a5)

array([[ 7.74596669, 14.14213562,  7.68114575,  4.69041576,  9.43398113],
       [ 7.87400787,  1.41421356,  5.09901951,  7.        ,  8.42614977],
       [ 4.58257569,  7.87400787,  4.        ,  6.32455532,  3.        ],
       [ 9.        ,  6.70820393,  5.65685425,  6.164414  ,  8.18535277],
       [ 8.94427191,  6.164414  ,  9.2736185 ,  3.        ,  8.48528137],
       [ 8.54400375,  9.32737905,  1.73205081,  7.41619849,  6.08276253]])

In [189]:
# For exponential power
np.exp(a5)

array([[1.14200739e+26, 7.22597377e+86, 4.20121040e+25, 3.58491285e+09,
        4.48961282e+38],
       [8.43835667e+26, 7.38905610e+00, 1.95729609e+11, 1.90734657e+21,
        6.83767123e+30],
       [1.31881573e+09, 8.43835667e+26, 8.88611052e+06, 2.35385267e+17,
        8.10308393e+03],
       [1.50609731e+35, 3.49342711e+19, 7.89629602e+13, 3.18559318e+16,
        1.25236317e+29],
       [5.54062238e+34, 3.18559318e+16, 2.23524660e+37, 8.10308393e+03,
        1.85867175e+31],
       [5.05239363e+31, 6.07603023e+37, 2.00855369e+01, 7.69478527e+23,
        1.17191424e+16]])

In [191]:
# for log
np.log10(a5)

array([[1.77815125, 2.30103   , 1.77085201, 1.34242268, 1.94939001],
       [1.79239169, 0.30103   , 1.41497335, 1.69019608, 1.85125835],
       [1.32221929, 1.79239169, 1.20411998, 1.60205999, 0.95424251],
       [1.90848502, 1.65321251, 1.50514998, 1.5797836 , 1.8260748 ],
       [1.90308999, 1.5797836 , 1.93449845, 0.95424251, 1.8573325 ],
       [1.86332286, 1.93951925, 0.47712125, 1.74036269, 1.56820172]])

In [194]:
list(range(0,10 , 2))

[0, 2, 4, 6, 8]

In [196]:
# normally jump is not possible in f;oat but in numpy we can do it
list(range(0,10 , 2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [201]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [202]:
np.arange(1.2,9.5,2.5)

array([1.2, 3.7, 6.2, 8.7])

In [206]:
# Linspace func
# to generate 25 no between 2 and 3
np.linspace(2,3,num = 25)

array([2.        , 2.04166667, 2.08333333, 2.125     , 2.16666667,
       2.20833333, 2.25      , 2.29166667, 2.33333333, 2.375     ,
       2.41666667, 2.45833333, 2.5       , 2.54166667, 2.58333333,
       2.625     , 2.66666667, 2.70833333, 2.75      , 2.79166667,
       2.83333333, 2.875     , 2.91666667, 2.95833333, 3.        ])

In [207]:
# if we want to know the stepsize then:
np.linspace(2,3,num = 25 , retstep = True)

(array([2.        , 2.04166667, 2.08333333, 2.125     , 2.16666667,
        2.20833333, 2.25      , 2.29166667, 2.33333333, 2.375     ,
        2.41666667, 2.45833333, 2.5       , 2.54166667, 2.58333333,
        2.625     , 2.66666667, 2.70833333, 2.75      , 2.79166667,
        2.83333333, 2.875     , 2.91666667, 2.95833333, 3.        ]),
 0.041666666666666664)

In [208]:
# when we want to generate in logscale
np.logspace(2,4,num = 5 , base = 10)

array([  100.        ,   316.22776602,  1000.        ,  3162.27766017,
       10000.        ])

In [210]:
np.eye(6) # for identity matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [211]:
# library for tools of plotting data 
!pip install cufflinks

  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68736 sha256=e0c3a9d18b6a8d6e7623d41d9ea74ade6ee6750ccfc1225550edb372a5e3a54a
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\29\b4\f8\2fd2206eeeba6ccad8167e4e8894b8c4ec27bf1342037fd136
Successfully built cufflinks


In [212]:
import cufflinks as cf 
import numpy as np
import pandas as pd 
import seaborn as sns


Matplotlib is building the font cache; this may take a moment.


In [213]:
# to print everything in offline mode
cf.go_offline()

In [214]:
# creating dataframe using random of numpy
df = pd.DataFrame(np.random.randn(100,3),columns=['A' , 'B' ,'C'])

In [215]:
df

A         B         C
0   0.434249 -0.223464 -0.060464
1   0.233524  2.894113 -0.421183
2  -0.737458 -0.123685  0.408492
3   0.210876  0.529158 -0.517106
4  -0.007213 -1.058987  0.301213
..       ...       ...       ...
95  1.878586  1.774486 -1.021309
96  0.714230  0.023278  1.411667
97  0.820609 -1.397491  0.049405
98 -1.773755  0.357426 -1.014827
99 -1.153514  0.651291 -0.370399

[100 rows x 3 columns]

In [218]:
#to plot data on a graph
df.iplot()

In [222]:
df1 = pd.DataFrame(np.random.randint(3,100,(100,1)))

In [223]:
df1

0
0   90
1   47
2   13
3   78
4   86
..  ..
95  73
96  36
97  34
98  19
99  30

[100 rows x 1 columns]

In [224]:
df1.iplot()

In [225]:
# click on  export to plot.ly 

In [227]:
df

A         B         C
0   0.434249 -0.223464 -0.060464
1   0.233524  2.894113 -0.421183
2  -0.737458 -0.123685  0.408492
3   0.210876  0.529158 -0.517106
4  -0.007213 -1.058987  0.301213
..       ...       ...       ...
95  1.878586  1.774486 -1.021309
96  0.714230  0.023278  1.411667
97  0.820609 -1.397491  0.049405
98 -1.773755  0.357426 -1.014827
99 -1.153514  0.651291 -0.370399

[100 rows x 3 columns]

In [228]:
# when we want to compare
df.iplot(x = 'A' , y = 'B',mode = 'markers')

In [230]:
df.iplot(x = 'A' , y = 'B')

In [231]:
# inbuilt datapacks 
df2 = sns.load_dataset('titanic')

In [232]:
df2

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [233]:
# relatio bw age and fare
df2.iplot(x = 'age' , y ='fare',mode = 'markers' )

In [234]:
df2.iplot(x = 'age' , y ='pclass',mode = 'markers' )

In [235]:
df2.iplot(x = 'fare' , y ='pclass',mode = 'markers' )

In [236]:
df2.iplot(kind = 'bar' , x = 'sex' , y = 'survived')